# डार्ट में अपवाद संभालन

अपवाद संभालन एक प्रक्रिया है जिसका उपयोग प्रोग्रामिंग भाषाओं में त्रुटियों के होने का सामना करने के लिए किया जाता है जो कार्यक्रम के निर्देशों की सामान्य प्रवाह को बाधित करती हैं।

डार्ट में, हमें अपवादों को संभालने के लिए निम्नलिखित तरीके मिलते हैं:

1. **try-catch**: हम अपवादों को संभालने के लिए `try-catch` ब्लॉक का उपयोग करते हैं। जो कोड एक अपवाद फेंक सकता है, वह `try` ब्लॉक के अंदर रखा जाता है और अपवाद को संभालने का कोड `catch` ब्लॉक में रखा जाता है।

    ```
    try {
      var result = 12 ~/ 0;
      print('परिणाम है $result');
    } catch(e) {
      print('एक त्रुटि हुई: $e');
    }
    ```

2. **on clause**: यदि अपवाद प्रकार ज्ञात है, तो इसे पकड़ने के लिए `on` क्लॉज़ का उपयोग करें।

    ```
    try {
      var result = 12 ~/ 0;
      print('परिणाम है $result');
    } on IntegerDivisionByZeroException {
      print('शून्य से विभाजन नहीं कर सकते');
    }
    ```

3. **finally clause**: चाहे एक अपवाद फेंका गया हो या नहीं, `finally` क्लॉज़ हमेशा निष्पादित होता है।

    ```
    try {
      var result = 12 ~/ 0;
      print('परिणाम है $result');
    } catch(e) {
      print('एक त्रुटि हुई: $e');
    } finally {
      print('यह finally क्लॉज़ है और हमेशा निष्पादित होता है।');
    }
    ```

याद रखें, उचित त्रुटि हैंडलिंग मजबूत कोड लिखने का एक महत्वपूर्ण हिस्सा है।
